# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- legalNotice.md
- about.md
- bids_example.md
- algoSubmission.md
- Gemfile
- Gemfile.lock

sass:
  style: compressed

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://munitquest.github.io/' #unsure where this shows
baseurl: ''
title: 'MUnitQuest'
description: 'Competition on motor unit idendification'
permalink: pretty
logo: "https://raw.githubusercontent.com/MUnitQuest/MUnitQuest.github.io/refs/heads/main/Images/logo_empty.jpeg" # logo in top left 

# Pagination
paginate: 5 # number of blog posts shown at once 
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Timeline
  url: /timeline/
- title: Rules
  url: /rules/  
- title: Submission and Registration
  url: /registration_and_submission/
#- title: Tmp
#  url: /metadata-form/
#- title: Algorithm Submission
#  url: /algoSubmission/  
#- title: About
#  url: /about/
#- title: FAQ
#  url: /faq/
#- title: Legal Notice
#  url: /legalNotice/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top" # always leads to "home" tab, even when clicked while in other tab 


